### ISSUE TITLE
Markbot said there should be a nav at the footer but I don't think so, and something else too

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/kraken-good-accessibility#1]
Hi, so Markbot said this to me: 
![Screen Shot 2020-10-08 at 4 23 08 PM](https://user-images.githubusercontent.com/55094125/95440524-3f29c580-0983-11eb-984b-8ebe4b032cac.png)

It seemed like markbot want me to put a nav into the footer but when I did it opposed it (just like my cat). Also, I had problem with matching the colour too. Help me ;-;

@hellachella 
@HannahDelaney
@mackenzierose

**Comment by MacKenzieRose** [comment]
Hi~ 

So this error is coming from an accessibility perspective, where if someone gets to the end of the chapter, they'll want to do the same things to navigate the book (like go to the next chapter). 

So if you take your `<nav>` code from your header (~line 22–40) and put it into a second `<footer>` at the very end of your `<main>` content, the error from Markbot should resolve itself. 

Also, make sure that you take the `role="navigation"` off of the second `<nav>` since that role should only appear once in an HTML file.

Let me know if that helps 🙂 

PS: I loved reading this issue tag; 12/10 content 😆

**Comment by hellachella** [comment]
Agreed. Cat anecdotes in issues for the win.

**Comment by MacKenzieRose** [comment]
I realized I didn't address your question about color! 

The error for your header content is because **your screenshots look like this**:
<img width="499" alt="Screen Shot 2020-10-14 at 9 43 57 AM" src="https://user-images.githubusercontent.com/19557909/96005363-fb5f1200-0e01-11eb-81f8-53ccf13a05f5.png">


but **they should look like this instead**:
<img width="454" alt="Screen Shot 2020-10-14 at 9 44 08 AM" src="https://user-images.githubusercontent.com/19557909/96005414-09149780-0e02-11eb-9aa4-d03652ba26f1.png">


What you have currently isn't enough value contrast between the text and background colour to meet accessible design standards.
